config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'cover_page#index'
  resources :workouts
    resources :motivations

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/motivation.rb
class Motivation < ApplicationRecord
end

app/models/workout.rb
class Workout < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cover_page_controller.rb
class CoverPageController < ApplicationController

  def index
  end
  
end

app/controllers/motivations_controller.rb
class MotivationsController < ApplicationController
 
 
  def index
    @motivation = Motivation.order("RANDOM()").first
  end

  def new
    @motivation = Motivation.new
  end

  def create
    @motivation = Motivation.create(motivation_params)
    redirect_to motivations_path
  end

  private

  def motivation_params
    params.require(:motivation).permit(:quote, :comment)
  end

  

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :find_workout, only: [:show, :edit]
  

  def index
    @workouts = Workout.all.order("created_at DESC")
  end

  def new
    @workout = Workout.new
  end

  def show
    @workout = Workout.find(params[:id]) 
  end

  def create
    @workout = Workout.new(workout_params)
    @workout.save
    redirect_to @workout
  end

  private

  def workout_params
    params.require(:workout).permit(:date, :workout, :length, :mood, :comments)
  end

  def find_workout
    @workout = Workout.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cover_page_helper.rb
module CoverPageHelper
end

app/helpers/motivations_helper.rb
module MotivationsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/cover_page/index.html.erb
<div class="hero">
  <div class="right">
    <div class="frosty">
      
      <h2>Track your workouts effortlessly and increase your motivation!</h2>
    </div>
  </div>
</div>

<br />
<br />

<div class="container">
  <div class="row">
    <div class="col">
      <h4>Log Workouts</h4>
        <p>Add your workout data each and every time you work out. Tracking your progress allows you to find and stay on the right path to fitness.</p>
    </div>
    <div class="col">
      <h4>Find Motivation</h4>
        <p>Battling workout boredom, weight loss plateaus, or injuries? Overcome any obstacle on your path to fitness with inspiring quotes as instant motivators.</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flexlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <%= link_to 'FLEXLOG', root_path, class: 'navbar-brand' %>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <li class="nav-item active">
        <li class="nav-item">
        <%= link_to 'Need a little push?', motivations_path, class: 'nav-link' %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item">
        <%= link_to new_workout_path, class: 'nav-link' do %>
          <i class="fa fa-plus-square" aria-hidden="true"></i>
          New Workout
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to 'Workout Log', workouts_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/motivations/index.html.erb
<br />
<br />
  <div class="booyah-box col-10 offset-1">
    <h1>Take your fitness to the next level with these intense-yet-inspiring words...</h1>
<br />
<br />

  <h1 class="font"><%= @motivation.quote %></h2>
  <h2> - <%= @motivation.comment %></h2>

<br class="clear" />
<br />
<br />

  <h3 class="fonti" ><%= link_to "I'd like another one", motivations_path %></h3>
  <br />
  <h3 class = "fonti" ><%= link_to "Add a quote", new_motivation_path %></h3>

  <br />
</div>

app/views/motivations/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Inspire someone today:</h1>
  <br />
  <%= simple_form_for @motivation do |f| %>
    <%= f.input :quote %>
    <%= f.input :comment %>

    <%= f.submit 'Add Quote', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/workouts/index.html.erb
<% @workouts.each do |workout| %>
  <div class="booyah-box col-10 offset-1">
    <%= link_to workout.date.strftime("%a %D"), workout_path(workout) %>
    <%= workout.workout %>
  </div>
<% end %>

app/views/workouts/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>New Workout</h1>
  <%= simple_form_for @workout do |f| %>
    <%= f.input :date %>
    <%= f.input :workout, label: "Which area did you work on?" %>
    <%= f.input :length, label: "How long did you work out?" %>
    <%= f.input :mood, label: "How were you feeling?", placeholder: "Good, excited, tired, etc." %>
    <%= f.input :comments, label: "Comments:", placeholder: "How did the workout go? What happened that was interesting? What supplements did you take today? Learn anything?" %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/workouts/show.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h2 class="text-center"><%= @workout.date.strftime("%a %D %I:%M %P") %></h2>
  <h2><%= @workout.workout %></h2>
  <h2><%= @workout.length %></h2>
  <h2><%= @workout.mood %></h2>
  <h2><%= @workout.comments %></h2>
</div>
<br />
<h1 class="container fonti"><%= link_to 'Back to My Workouts', workouts_path %></h1>